# Generated by Django 5.0 on 2024-01-19 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arquero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('pie_habil', models.CharField(max_length=20)),
                ('cant_clubes_anteriores', models.IntegerField()),
                ('telefono', models.IntegerField()),
                ('estatura', models.FloatField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Defensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('pie_habil', models.CharField(max_length=20)),
                ('cant_clubes_anteriores', models.IntegerField()),
                ('telefono', models.IntegerField()),
                ('estatura', models.FloatField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Delantero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('pie_habil', models.CharField(max_length=20)),
                ('cant_clubes_anteriores', models.IntegerField()),
                ('telefono', models.IntegerField()),
                ('estatura', models.FloatField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Mediocampista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('pie_habil', models.CharField(max_length=20)),
                ('cant_clubes_anteriores', models.IntegerField()),
                ('telefono', models.IntegerField()),
                ('estatura', models.FloatField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
