# Generated by Django 5.0 on 2024-01-30 03:41

import app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Arquero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('pie_habil', models.CharField(max_length=20)),
                ('cant_clubes_anteriores', models.IntegerField()),
                ('telefono', models.IntegerField()),
                ('estatura', models.FloatField()),
                ('email', models.EmailField(max_length=254)),
                ('fecha_nacimiento', models.DateTimeField(default=app.models.calcular_fecha_nacimiento_predeterminada)),
                ('descripcion', models.CharField(max_length=300)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='avatares')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Defensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('pie_habil', models.CharField(max_length=20)),
                ('cant_clubes_anteriores', models.IntegerField()),
                ('telefono', models.IntegerField()),
                ('estatura', models.FloatField()),
                ('email', models.EmailField(max_length=254)),
                ('fecha_nacimiento', models.DateTimeField(default=app.models.calcular_fecha_nacimiento_predeterminada)),
                ('descripcion', models.CharField(max_length=300)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Delantero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('pie_habil', models.CharField(max_length=20)),
                ('cant_clubes_anteriores', models.IntegerField()),
                ('telefono', models.IntegerField()),
                ('estatura', models.FloatField()),
                ('email', models.EmailField(max_length=254)),
                ('fecha_nacimiento', models.DateTimeField(default=app.models.calcular_fecha_nacimiento_predeterminada)),
                ('descripcion', models.CharField(max_length=300)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mediocampista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('pie_habil', models.CharField(max_length=20)),
                ('cant_clubes_anteriores', models.IntegerField()),
                ('telefono', models.IntegerField()),
                ('estatura', models.FloatField()),
                ('email', models.EmailField(max_length=254)),
                ('fecha_nacimiento', models.DateTimeField(default=app.models.calcular_fecha_nacimiento_predeterminada)),
                ('descripcion', models.CharField(max_length=300)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
