# Generated by Django 5.0 on 2024-02-04 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquero',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
        migrations.AddField(
            model_name='defensor',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
        migrations.AddField(
            model_name='delantero',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
        migrations.AddField(
            model_name='mediocampista',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
    ]
