# Generated by Django 5.0 on 2024-01-19 00:39

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquero',
            name='fecha_nacimiento',
            field=models.DateTimeField(default=app.models.calcular_fecha_nacimiento_predeterminada),
        ),
        migrations.AddField(
            model_name='defensor',
            name='fecha_nacimiento',
            field=models.DateTimeField(default=app.models.calcular_fecha_nacimiento_predeterminada),
        ),
        migrations.AddField(
            model_name='delantero',
            name='fecha_nacimiento',
            field=models.DateTimeField(default=app.models.calcular_fecha_nacimiento_predeterminada),
        ),
        migrations.AddField(
            model_name='mediocampista',
            name='fecha_nacimiento',
            field=models.DateTimeField(default=app.models.calcular_fecha_nacimiento_predeterminada),
        ),
    ]
