# Generated by Django 5.0 on 2024-01-27 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='imagen',
            new_name='image',
        ),
    ]
